---
nfs_servers:
  hosts:
    k3s-nfs.k8s.cloud-milky.solufit.net:

  vars:
    ansible_user: ubuntu # Match the user from k3s inventory
    ansible_port: 22
    nfs_export_path: "/srv/nfs/k3s"
    nfs_allowed_network: "10.2.0.0/24"
