---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: infrastructure
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.5.15
    helm:
      values: |
        admin:
          existingSecret: grafana-admin-secret
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: VictoriaMetrics
                type: prometheus
                url: http://vmsingle-victoria-metrics-k8s-stack.monitoring.svc.cluster.local:8428

                isDefault: false
                editable: true
              - name: Loki
                type: loki
                access: proxy
                url: http://loki.monitoring.svc.cluster.local:3100
                isDefault: false
                editable: true
        dashboards:
          default:
            loki:
              gnetId: 15146
              revision: 1
              datasource: Loki
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
              - name: default
                orgId: 1
                folder: ""
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
                  foldersFromFilesStructure: false

        persistence:
          enabled: true
          size: 1Gi
          storageClassName: longhorn
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        service:
          type: ClusterIP
        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            labelValue: "1"
            searchNamespace: monitoring
          datasources:
            enabled: true
            label: grafana_datasource
            labelValue: "1"
            searchNamespace: monitoring
        ingress:
          enabled: true
          path: /
          pathType: Prefix
          ingressClassName: cloudflare-tunnel
          hosts:
            - grafana-k8s.lapis-dev.work

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
