---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAN0V4DHy1iB6qgm/zNkXhHlUJ1xLmAmhPjDWSfnihBRLYaS3Y/+0w8NcP0Z0iyr8RHfKEIqQeqyRa/nfEMdA3tA0+kJvkIIGUs5QEzfEiqAiBl4L/7x4SuhlyNpmmc8gccnTFM/XanTMSPWIjJkHekHMRPhqDzPzHgTrB4xpXC6oiLXRc6bFL9fpireVsbl9+Az2/NwrY2jFHr/JHdbK2Ymk8bMg6ex/01UnY4CNpBGkFIB+QsaMTyZNLRr9v/Mxlc6ql3M04MLG3f+UbFtMdf9JDq9q6J7LGiAi6ixQxEPYqJf2FAM8LYWo4mvRmgS6WcSQ5v9O4VdinUW4kgHTMyX9UoUD27bBa87469DsyWxKpeU/lRRvJeTxWf/7Ibt9kQ36pi41A7KwKUTdOuqGt4CfbHMpgwpIKxqrZv2p+zAS3cqHpEfM7Te6rtP8gGvZMmtJOfZ86KRZllFFKGE3RtSc8kHH2E8RsQr5xRW/nYuKar7OjfE/cCt7aQvNCho4vlgeD3CdS9AliAYif75jYi3ZWrnkHrz1iL8YcBmkNO3/0+D8HvTEbr3Pp+R/yZ/Upiw4hiBelxCFGFj4suk9rD3J71UwJCKN7N5KloOCHW+K0c3i/nQ0aFNW04jet6ppi1gRjsAXJXwdPoTC3/GHvK6gSvRBwe3cTYt73cc+6czoOiMmA6DOr0MAiHkr5jC+HxtL4o8g1ki42poAtvEA==
    admin-user: AgA+a8D/upO7D4y5PbWfzvPVTpGsb1oL8wRdVZzxSMu2ZC2I1zelgEHRccQhsL9gyCEsl/OuLBam3a7VzU3HjAy4H2603t7IzPBIlGkdmxwznAnksggcBBMxRU/rxEVoROT+2PO9pxgR4Iu0BvkMwaJ+cFBXbDOqo+ZlvU89g/UQP4NsWe0xB7jT6KF3dofzjFzXxunqgo/XNSAaLhzHLD6jwnnSVOfEnp5m/e84ruegHpLbXC8dcnkgiOaJHcgSKpvqlOEA4xWuiU1u+vAfdqSelpNG5Tuib+TONDtUMaVqz2rQ02WUmV1pmgtwMvcrE8f6PCx843HD1aDpsbIoRPaepmt/pjMpJEcfQBRZm1H0YXWDQMfxadhqtzs8SyPUt+NZTJceCdXEQYb3kn+jFeZ7u96QneV3FWNQIvieNjdcZRSjLlEqOaH38CCJUnd6B+eTYC6/EdPNLRHRIOcObDmwTCN5ogNFGBSbOSFCfQ6WOEEbS3G+Dwfju4hIMfjyRv05KGg063ohlBez3n4uZvtvnDfWQWXyhMlmtmlJMwbF7xwsrpcZdVS/8Ni+lhtP4c0XFMXIo2CoCP5folU6A8WRTVx+CaUl+zdCH+uNyKuIC8UbmNniP2t3d4O5cBuSeKCgZwZfapaLuoRsamC7niDEGb646cFp98TFPAKfbmDPJBK5nl1CDv2Xc2EB5reG5RA7nQnYuw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
