---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-alerting-secrets
  namespace: monitoring
spec:
  encryptedData:
    discord-webhook-url: AgCIFvaUInrVfejYlRreMJJFxt7pfn3D+ZIGea2k3Gj9UjTE2ULunx+eMQ2ZaNT98tgzBqo3aREbQwrfv7PQk6AXjJGbdNmRfCnkp6rowO4Pd/nM3JNtaFyRT159OiXjzoDsygBI78E2CWmiXAaU/gf2c8fYPZLrlgvHzGu83p8Ld1/n8jo0Ets5hi30r6kDpVI4O7l5SfXhWW8q5TauT0SzWBklUkmi/hzIJg3L+0hz1h9ll8OlqhY9Jfr+6vYXloKqPl/EYqqaXZXaGFBCHi8cZwrfqHzoBlu0OfYxFxBPneVpAocDfDKNA8+x+MrtVc+9+EeIx/3EMKPFarFVWIe90y1mc/L3Pzl7sqf8PFpTkGCIaQbJQEjyAK40yLzVgihDE/4eXJKyfr4lwth0KFSd5tXEZ/2q7bhVu7sARgXgdfAvej95rTWmjR32uLgy3c13WtHnoMTVWagmIfl8luENiC/PtJ8RSZZLHpsaMoIkK25mkIG6Vxl3tLG/T1dhfZazwcFiqIrQW4VOQu2pSElK0hST9J4UwrEwbHRTpyiZcvwsB0Drs/cNeQ3EMxNk/zP7cCWixT6BCNwzigrdNLsrvoZjGHDt4PzVKqSI/sL9GataAZtFckvJBzt/3FK6HvGdByPXSgLHjbksKMgKRj5gRpVvXoXInvUpJhXeFC+tHeCJK1AdNVboPV4dlcU7oa6rkO3IY5QQe/EKJFBpTvxNGW7JOfxXyUjKaXv3OLPl0b2Vaz0TxxlLH4P+v4X9puPGus2aCdT6nGHw062tahKyAG1XR+6BFivPSyWlZmqE6fJjJX9LQ9npT//Pciss8HKYYa5TVjyZUAMI8QBU7KjE/mlw0asFzQh2
  template:
    metadata:
      name: grafana-alerting-secrets
      namespace: monitoring
