---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgA1mi+3Wg90cOb9wWiJh8FR4Lw+vSq3hSRRoPgVq3vzATIyUV7vyqmY0Q40AsXHJJ4HS0NF8A71lNVV7Tqbkd+Dj05/pfb/6lESbe/siAMk6nw2ADvc+X4bKHPxkxqwUqIB7OACH/nnzfogPSPqXnS8GJSVnXs7YG2vgTX/I81vFD5RZLtv5PvqaSDPDFRF97Y/fwoPcX/ioSm7SC8Q+iHFLXASTQvDx9SDhS12VlgMoSyS0rN7ggZZ7/oUXbM+cmuiqWKDV/lrTljDZy7WL+q8eaMwHnmaMHAcEsQm9cyXqsRRq+ycRDzBjxexoWzziuEUp6OqzfVq8/u/LuBqGLztUzxU2P1oceG2hXVtcmJhy2aMd4mHyljUrYErw53gWHZF3oKfQ69QRspIc3mQXOAFK+28mXX8us5e8lTr40l9VPG5itAMcoiwuJWfRbI0k9QMYaBeOPbfzGS6K9S79XJN/yrsKDFHSIBoewMH4h/HWo5ZPzPugVwj8cdD+BpzblpUSPNjQslliLRvK5AesjcwLVjOTlvpT0UkMl4PYvWne6Yr1JneK7+T4M3m0cK7g9meT+gnoFA30AcUQHcLTAmYc/5auArxD9ucb7INehLTa+/uu8es8ciBuaDunoj60wjciU9HnN5UjWe5lNihzY4nvEbHpt8EtranW2c++MAsWW/BHSX4kUEZ6QhliCvZ7GFjf1334AmfdmvnxyI4kQ==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
