---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-public
  namespace: dawarich
  labels:
    app: dawarich
    app.kubernetes.io/name: dawarich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-watched
  namespace: dawarich
  labels:
    app: dawarich
    app.kubernetes.io/name: dawarich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
