apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: dawarich-sidekiq
  name: dawarich-sidekiq
spec:
  containers:
    - args:
        - sidekiq
      command:
        - sidekiq-entrypoint.sh
      env:
        - name: APPLICATION_HOSTS
          value: localhost,::1,127.0.0.1
        - name: APPLICATION_PROTOCOL
          value: http
        - name: BACKGROUND_PROCESSING_CONCURRENCY
          value: "5"
        - name: DATABASE_HOST
          value: dawarich-db
        - name: DATABASE_NAME
          value: dawarich_development
        - name: DATABASE_PASSWORD
          value: password
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          value: postgres
        - name: PROMETHEUS_EXPORTER_ENABLED
          value: "false"
        - name: PROMETHEUS_EXPORTER_HOST
          value: dawarich_app
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9394"
        - name: RAILS_ENV
          value: production
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: REDIS_URL
          value: redis://dawarich-redis:6379
        - name: SECRET_KEY_BASE
          value: '"CHANGE_ME"'
        - name: SELF_HOSTED
          value: "true"
        - name: STORE_GEODATA
          value: "true"
      image: freikin/dawarich:latest
      livenessProbe:
        exec:
          command:
            - pgrep -f sidekiq
        failureThreshold: 30
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 10
      name: dawarich-sidekiq
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /var/app/public
          name: dawarich-public
        - mountPath: /var/app/tmp/imports/watched
          name: dawarich-watched
        - mountPath: /var/app/storage
          name: dawarich-storage
  restartPolicy: OnFailure
  volumes:
    - name: dawarich-public
      persistentVolumeClaim:
        claimName: dawarich-public
    - name: dawarich-watched
      persistentVolumeClaim:
        claimName: dawarich-watched
    - name: dawarich-storage
      persistentVolumeClaim:
        claimName: dawarich-storage
