apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: firecrawl
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Walkmana-25/homelab.git
    path: k8s/apps/firecrawl
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: firecrawl
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
