---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dawarich-postgres
  namespace: dawarich
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: application
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-minimal-trixie

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: dawarich
      owner: dawarich
      secret:
        name: dawarich-postgres-auth
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS postgis;

  postgresql:
    extensions:
      - name: postgis
        image:
          reference: ghcr.io/cloudnative-pg/postgis-extension:3.6.2-18-trixie
        ld_library_path:
          - system

  storage:
    size: 10Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
