---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openwebui-secrets
  namespace: openwebui
spec:
  encryptedData:
    openai-api-keys: AgCjpaYv6RL8EvePepm1lU2D8zBQCeaB/N8Dm5wLkhi5A75+JvY+4TbOZvhIGVctSWOHdy5FWMrR5MFNT/CTo3uWZflF8LMmQiLuRHXhqN5emjNkRN/JEFMKySlfoUTu8k7C8az+FBhZgOrVcZNoFidDEwPkORLBRBG5FSKpMPzyURTAyL/eem5UzEQgFs2evUlfOsT50/P5BW2lSeRrEhQEPea88Nf58nI7rxHp3yQ19ueDEOnvGuJUQaal1seRCyco5i3eBZWsBwdcDsU47S7E5N10Pg0yj7yQBD5uwB81OlQlsgX7wo8buCdWv3ljs0BgH2a1FjbqQDE5WIc4j+jqaCPILkmLn6cUpUe7alJhmeq4f5i5yh8PKVcdxVJl1uRauVcT46BoBKPMlypALqPdJh/kMuXRbZoKO58Vmqd7tMJLtEX2rdhpJ6QdoABL8RSb2GzFWICCk8oJzdkGOwea1PkHthBc67hsyZpY/261Fo37WE3Ai9UwNKrkBVSSHgboIJ8hI84qyp+3MenGOOzU53M1l9LFrjPL/wXO3tdsNMER1mLgjfpaUYUE0isocn2mtKpzMVqELh3inN7V17WqpmrYAvEnmEP4frKL8jbAT16HEXLM6wlYjTiy44Y25xmvf66eGuo1IGdyE8OmzYquWG9WQuMZPo6nK2u6T4HyR29fRKcEiao8tZeRV4q0/yTAOgukh9ytqJWmFA/cNg1fFH2p5szooU9aYkrhI4q728yE7oKRrkcifs+DZKpMSjiXuI0Cj5Geu202xaXmr3ICAuGcRBYiGXf78tffBelOazmZzZtZC0Tdf9vy9BXuuNQdblFdq8KmissVFC5daW7L0ve9TOMJviqmprWlmZsx7+3ReDMFPRP4ug==
    webui-secret-key: AgAQZCJoEaFxhBBpBgGvAC1JoytRFwkN8iZIN0jbs14FrVUU80lTQyYLRGl4dHJqjLwIjlKb6rQ+MQrBYy2kQ3iYI0Llt5prfj+WgNGxrNbdQ9yJcW/szvMJ/yyyuIQUTxBi4khWWZ/3qiR9rAJcoUwHmNygUrkQeV8cCn9oCiUZq3hqDLXLm1A7WXcVS7CeblgtHxZxg8a/FIUINPfOyBv/bcT+XKExmDFiPe6oFN2dPnFrdD2jqGCaBoMM3yOosIjaxysqffpIHaXqQZqlGhaNq3tJH8hbxyuH5t2HYEnDEn/sWllXMWFp2gXTvs2gZ2yTb+fsi4kCmvomlSzWqokLqwexVAD0Vnq2F+93lkYhoiCNOBX0yojbjuhxAmEmdCqNbR9V8EQ50r6pqXmuC88w+XGP1GcHOoe2BO9cWxdjAzwftgepck6gUD3/gKDDRGFSi9bmJL8DCX7edDz/3/jzUeOoVCs4NLebNY0KWNXgNynXbtvyL+ffkjNk0dyRXgD4qIYCnwQySdLn7pf6Mfrnw6ynwwiYESV/QIOExzoFEv3pk5em5CQkmYTVZdozMB0ysOKOAACj/dEDSyKRZZmpiZRYuMweF6lgimcz+aiPUxvlY38sIp5gI9sQs5YydyzhrKhNJgekogiO/M5U9vQJSpEOpa/OS4LnidSGslkUAFaiH0fSf54qa/UKs/fGdJaOBVurk3unvuttcnnfAiYOVKRO4AqB3FlukYXq4AGYRDSg3BvstHJIHjNJhfqh0fPQVP7nkoGBI+uGpK1W9Bug
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: application
      name: openwebui-secrets
      namespace: openwebui
    type: Opaque
