apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-secrets
  - cert-manager
  - metallb
  - metallb-config
  - nfs-provisioner
  - longhorn
  - cloudflare-tunnel-ingress-controller
  - victoria-metrics
  - grafana
  - headlamp
  - argocd-ingress
