---
nfs_export_path: "/srv/nfs/k3s"
nfs_allowed_network: "192.16.35.0/24"

# Block device configuration for NFS storage
nfs_block_device: "/dev/sdb"
nfs_filesystem_type: "ext4"
nfs_mount_point: "/srv/nfs"
