---
apiVersion: v1
kind: Service
metadata:
  name: loki-loadbalancer
  namespace: monitoring
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/part-of: infrastructure
  annotations:
    metallb.io/loadBalancerIPs: 10.2.0.110
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: loki
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
