{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "cloudflare-tunnel-credentials",
    "namespace": "cloudflare-tunnel-ingress-controller"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "cloudflare-tunnel-credentials",
        "namespace": "cloudflare-tunnel-ingress-controller"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "account_id": "AgCXecdwuYxh4Gdbuclh13D6W9+VMWurUSpQFNIJ5sp0ePL0AhTWAqCwafv+EXi7cb6StEvXgNusipV+/UR+MA5WPUMrpcJxhARdljpb3CW3ZEDitQYj6GMk7KDZQVKcO9iK+6DLvlmlUDFGQ9vhe2S8Ozt4d4Jnd7N2dsQz2AXmLFtH+EQJ6ep10QBsU31XHxQ0BPJeUqhevxlN5xFjp9GW124QwtBTst2bya9UofHHtfIpegWWun5ZV6shfdu4FmWe40CUfiNsAlJ7z8pVBb0rqAX5SKJDP+GdJoml+yqp3CvhERO72tVS8aonEzNZ5kwWgUPojDxol68/TXCECCIT7/wKLuCZeLCxUvpAZuTchCro6CgxAgAvsV/RvjDg6IHBHUGTErwEgErw3n0mmPf39Sbl3DSWWpDO+L6Mex4BEG2SwqPo77FeGnwxNlygib7J/mGPYSno6d3PXkYITJwvhbwofzL66+h3A/STpka7UZ4F9ZvKwXvgD2x6Oup3AUXH7kLwh4rQT6611EB0F+GSoZCH3lbZYLc/sJ1rgKnKSfmEFafCLtxIex4NklL3PHG6v9gMLLByzBtpbFkjDzMtK5DBR8nUDfRmUfesLzCSgDQuOgkFPyX048WCBtdwS+DVrr9s9Z0mZGo1udZCepb0e3CH8tL9hjsKXOoVXIfeeT+gVphp41zs4GTDvOw+RFKynCJtkXT8jm5Ho748A+y7QhCX+TV0zVuitfF1bO0JQA==",
      "api_token": "AgAEqfBBHUDyJyWCS9A3pf0m0yMeUdZGeYNHa2P0xyT4ctgojfsNZwoLZVWgf7RTZLTKkyHmVSM9pompbhgNplWC/LAq8fFNMFqSKTp2mx9O0KcMExOgRYfx+aNpUnVUvRjbvi02e9hz07x2O4H2HawmvEnRem6wGgiOSY5+mgY8bu4o6ki85UB11DBvosWwqllsWbbn7r5Qwvs+wVMSjqG/XmDuZZ2LS5qec1/VFh+sj9sbcFDWX1XJy0jZ5UJgQ9NHefkauJTINQn6UFlcnuLQMIrDNrkQG/RSJ3Bs4dY3xrTYRKN8iHPuV30tmGVEmTbr4NAZyIGu8a0BxU1StnEoYEkbFuIbNt83HrpwAkOYBYlT0D2ymnDJLjkO39UXn/mklQndCQ2tEaP1FIc8JZS1eb/EZ7bY4rA1kaKhy/JCwMdxeKbRNSMyJKRewiLiKW2Q3Kg+oFRCiqmnWVz9BpPnk9W9ycwt2i5vxa5SCFv2k7whd3saNEu5SBYZhTRuYcKUHiNHLFOmoAOs6DvbflkM7kpYiH3vUpQp42leOVGpkZsUUd9fMcG7cpz9imm5vc/cVRHrZFb6S47BsGVHZlulDOtlVwGjUj40b2nvO2eW2z73yX6fcKG8hfkZqM8hGUdgqBrKtkCOhYKg9+mcrJiF38Ny+LdlszGls1wUrmMyNndvcUfWduPt9k70UQiyjq6lPKko8xX/FkzizKLyALC4EmF+c2yzpZwSM2GiasxaKvzhkTlG/IDMZ6TwVZUSoXGLOevmHw==",
      "tunnel_name": "AgAQcIuZfmvRF+Zy05Er5VF1uqKGESkBKW+FjPA7csTYqeSW5MsUqGMPc2j9RJyDyYt13bcbKdy/E8eVEC0jszcFT/McvkVbleh2GlSarPF+WDbwZDwCK6ed6rlFWJSL2/QeKuQm7ol2j/7C+g+ctcrzJPSn4yVUpF+Nb1/CmmocatHPSMdkB7EnZ/CokLpzgQaRuOZ6H/ILzR4Aa6q22mPpJvblgr3RA7mU7szl5jHGVcKCHVCJLcLoOb+zQSHLOdyHKzOQebNplVtZNE3ajGPn2wc53x2DDFG4uoTrlxuJBHLDxm9FRlay3mkI3byajqrWkZpCgfALRdM8wodyBjLgGCAeVornklvHTjJfajJLyeFBfQefW7quMqaJlH/7Imo/yQZGeyUXGvddMTmvAGhlyQ94yFu8+9MxcWFG810U2IHtPUQTogdkCr59FZ9SVrns7fmYxHs/DmjT4AslASTeBL57e7XUhNetTv0q3EfFd8ul0ekZGyJq89AJCnWIIi2PJyplEND6+WRIBbAVyjFVA5dhkIRsK066f6crBSz/FX04CdHt+RZc4Dj/+X+/A6ThwpXx5anHarK4N9ArgAXNBcbx6LF55hts9VvP+/rYYucN8wt13ih0uC+hWU+/aDDLGG+4Vs4zqcC666epo+AWgGSQhQYQrItALwArr+CdgVyT8dry1/3H+JQHOCRtIG/dOnQ="
    }
  }
}
