---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: technitium-sd-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgANQb9uRyJ2BGxDBdZUYtMfKL/odrKmyTDGopx8EXjYLjleaqqXHnkDaYJOXfD8zduL/RgcQVwzD9lGWWi3nLWEyuMJ/Up6Y+vYQOQ0hNAn0T8WTEgykatFlUl5lsjjB43aZZPvRaiNFLEkDZuvqaYHeQ2xoOotS5ydcQuFUO20ujC98+coPQ1clkZB9mHqRYC6KDaVJJGFmN54ZyFO/fK6UiWilsWQyYQHSidNIUu5LdfnAtzoQ52+ZxdjCcpBNAuzUUoJEFgaJlgr0sVUpChULXg+MBWD6ihVccMa9IE64cF3J6UezrXoN4U2Vq4Z4ud1N8hiJK3c50yfJNRNH+Hw+TFJWEvSbPUg4rT9UUzydE0wGCSnkXbk3Yyqd950egOMaErElvBBoFskHdNUp66Q25cw90hZyURGIyUqA1pe6oe90INu6PT3iJKYnvl6nvoVc5Ab/4QHBImIeoeN+CHg3myUrZCMgPpc2aB9EXtDmdtAuzkcFz+EUUbc4ovuIajj5kgi7leDxEQz/bML24T+kB+mPQSuEQwmFVf267Utw9XGB7JsFuXK4ULgNAB3mA0qyw4/jLQjFfW8sa8gIJswxxvkjWMz8jP+qfIW7K/xgqZlShuWh2dyJ9U0I4hT5Wo6KAxZgtDMibGIUIABWse3n/3PHqvD6qSgKoAfZ0Pep0B0P1KWHWcIX4k6Iw0UblVnlHgCFYjI3vvU/MfngrX7643FqFIW/XQng4Xcq35Rrw5VIpoZmbQrWoODeb1gMasqVaUN98RZdVvNZp157//Z
  template:
    metadata:
      name: technitium-sd-token
      namespace: monitoring
