apiVersion: batch/v1
kind: CronJob
metadata:
  name: drive-1
  namespace: simpleapp
spec:
  schedule: "0,30 8-23,0-1 * * *"
  timeZone: Asia/Tokyo
  concurrencyPolicy: Forbid # ★二重起動を防ぐために追加
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300 # ★ Lを小文字に修正
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: drive
            image: harbor-k3s.lapis-dev.work/apps/driving-school-bot:latest
            imagePullPolicy: IfNotPresent
          imagePullSecrets:
          - name: registry-sealed
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: drive-2
  namespace: simpleapp
spec:
  schedule: "10,20,40,50 9-20 * * *"
  timeZone: Asia/Tokyo
  concurrencyPolicy: Forbid # ★二重起動を防ぐために追加
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300 # ★ Lを小文字に修正
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: drive
            image: harbor-k3s.lapis-dev.work/apps/driving-school-bot:latest
            imagePullPolicy: IfNotPresent
          imagePullSecrets:
          - name: registry-sealed
          restartPolicy: OnFailure