apiVersion: batch/v1
kind: CronJob
metadata:
  name: drive-1
  namespace: simpleapp
spec:
  schedule: "0,30 0-16,21-23 * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drive
            image: harbor-k3s.lapis-dev.work/apps/driving-school-bot:latest
            imagePullPolicy: IfNotPresent
          imagePullSecrets:
          - name: registry-sealed
          restartPolicy: OnFailure

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: drive-2
  namespace: simpleapp
spec:
  schedule: "*/10 17-19 * * *"
  timeZone: Asia/Tokyo
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drive
            image: harbor-k3s.lapis-dev.work/apps/driving-school-bot:latest
            imagePullPolicy: IfNotPresent
          imagePullSecrets:
          - name: registry-sealed
          restartPolicy: OnFailure
