---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: registry-sealed
  namespace: simpleapp
spec:
  encryptedData:
    .dockerconfigjson: AgBdvf87+ZMsIdnAGhkVJJRlDkBM9P4gRj5ix1ButwAVK8bKGYP3nTBbxGIlOoKGh1sbGFwLk9r5HrJaRiRcOYILFmtUkAX+ICazoKG64evHMwULf/ovJ1ygKzRQRepLaxwG9WwEFFkuDdHpnTbpDeXQtYmtonXFmgEMxlVPqUvOrD9GfkKUY1VsYbEatwIC5uNxQaZ8Cp02/GUS2CV4m1GHrsuU2BLVC7yrRsFJ8YIrw2dKe0WyE5/ScY2ZOZtutTCqlsV8qkKIptdGbS2hnvZ4kWvkdAfkj6flLYFQkJB7zpNL3FHuH4MCtF4NHpYxHwmUZNPqEZaSQllqv8pXAH4EYUSaJuErBJQcNNlm/i+vARGZ08XzIcmlWNWHL3JpuszDj9PROLUBNWO26HEPsrPdJxLHuJUVEXwLxJ+7mgPbaEEQwsr5Nbp4w/4qrtpCFHg4nvRHKMmtwMnQzapMKmRCc669N0PPOW64Qg5APhEjZNPP9riN6v67md/g/D5Od/G+JP0WsnQxmXJ0QpyLj539LlMn6HTbIc7V5jA9nFcU9e+MXCp4UJTYwHYMldEltyJj+fvilEMczvEziJjhlchb2IldtLRaLWo0n+8AnAl0F09MlaiY/8UvJ/6i4Kf6WcLk6poyqkX6tIj/g5vLa2u3Ed2SYJ1Tzq8N2ylrW2msv7qpct35RQYK6rNU5buO8Kt9VT93vpIMXwsh95rr+XJFBrrsDrqPzfs6shOG6+gQkWvdepmmT/aw+mOhAPV6hmGylO9oEgnSmqzfgb2rRP4W32KtUHh1UUVLnwUZqzVVxCwjqgoeXt7qxje9beeorD22NMEJjQAVQ2A1gPjKYbiH//KbSkWY9OnY07tasCENBqLlnJ+eFILxUkty3mkVVv7juJI1wUWWd8pNhTVc/iSw9foE7Yj/U4LKrix8zJQbmf5OS1MzmLa2DzLGlvej+i6NAxpySn9b63nrxBCel1ygq2eFv5OCu/V1
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: registry
      namespace: simpleapp
    type: kubernetes.io/dockerconfigjson
