---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-core-secret
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgAxxYEoXZu6IAfUv4tPB5G+oaz7UZGs9VZ8qdnLAPrfN16oAUR0U3IyQBJ/rtuclAKtAe1cSwM82TnCCIiahP+jYPpyFCAdmaSAQdFFFYvFfgw98InD1ADSRAFsPeTtSIVPPNr/0ZuPJc3jRRe7CRdvmA7lg2YNHMmo4pT74Q+zgzswCsEArtQxPG7eMY3eTyt3PD6kRoLZhRJougfvxNLXRZ7uwDaJLdVPr+pQH9PP1Rvs4BCTwarR+RFVRiX3G9V7zXDn/rrHwGUrjBHIdehyxsiiLDoeW+DgiVf0xUneWM3ye0jKJ/Sjw1OJ6c/D1iVpCdRfawLBT/5dbVggWsZ8q3mTcJRPugY1R0Etv0Qf9ArvqEzBKDZx0vExDPyghMdhgEuF1N5vSCLVomAunqFWFncFp7ezuwOkv23/gEZ+HMcl2Ch/Uy9vDnjIA5GSu+iU8qLmEoziPc4kVsHs84v0I5UzUnOhQ1Q9OyA/eDxLEXNL1tKlcqYyidI5N/Uqk6+eTtugKPiHPX49fyfFuK1s3Omqh+C3oRYgF6nDPsCul5LHiGW4+07YXoKkuy/CAXY+WDl7sRFjaw0T+JI1y2s2QbHZDq83cHB4cVZo/GgO5whkAe1cP4cLOeJKX2mf8lF3oh99LlRpfpscop8uiGV7EO3KbuGMLAmp5qN5mNGmKarwaOwZiR1FvHKBVgvHHQsm4Vwjd8hF1BfMoQ==
    secretKey: AgAdM0n+g2Njx2YXhKYX+CCcOybPiR8YIdVmdn8frBnP6oyXJmOJBrv8hAruwDo01GWZxM47vUd4YlyzmUUipRtY6c4KL0j+yWTqicT1+O2mRIcq8CMFX2NWbJGSO9qNaPTkelJ/OwGdvcCMmt1kGi4iLKT90P4DsBU1i75VSuVbqGHTNTyhNUKdWkg+MzeAeyb1mXvL9SEfnR+fzKjiaOiquXlgRwCI7ueH0VfHNS48h7HbZX9yrGowhpWlGRlUsWHBxWOti4VEAV7JyrLW+QBPP29WqbsmIgDd3lsOnVyDtVjY164Q0e45NnRY2phI1bjbXsT3XO4rTDGBrx/Ur8CXDm70R0F64PbcCNwutWBl4VnkvpJm59hrvEuS6N5JJnIbKFYwmbjYbtrExmlFDRpy2v1wawB6zxGHKKu8+GVDw2n9781w2DlMF/fc+64FrZB9KYmfqFfahxG16x+t9n/EPD1ZioIhEuumVDuM3+a9WXIVR8pG09iwHOgj6Z22a1bHXRD79kkDM9Q3THkXghMLbKFH+r2sHq5pNH8Vy3GW2F1YgeBm465unKXg85631ammakYf8tFN6/t+UQDEJw39CtiI8jgvjyf1y45EC+46ibRsYETDoPqFGkzJeSHhXDaEQdDfRUIHGq7EvRrEuqO0deezAzqyUTEyA6jV5ZdiGdMnwv8tm/lzxsayqQsEmV7oa8viuNPl5dzGSmZEhxXG
  template:
    metadata:
      name: harbor-core-secret
      namespace: harbor
