---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: harbor-registry-auth
  namespace: harbor
spec:
  encryptedData:
    password: AgCVyjdWgegq4EnfODjXY7NP3fW0oM50L3+Wcc7C2B9r384qVoBtQQFsI09AtVQHZgzCq58UIP36GdGR8d2ZPN14Yn6eIFO2BcgMmchjVCD/uQGRtBWYjx0afswOt1MO0GJXJutkGveleujiC+UbpyL/gIjg+PdPrhCQDmQv6mTXHGwcporPg8Y9LonmB/ruIwWO9JvQLvp9/h/tNXqIwDSJiH8Gc1odZkdYa6D0fd/+qQaySXlQX6LK9hWxqQBblnQ704q+MEIcMGcxSmRLLLPsXaqHP/nBt3pIfcPjt231B2KGuav6KTCZnSM1muzVo8Pn7K2ewznAuqzLgsoO5PJ+49fvdqLRJ5ymWqqttxsGFrt/kbAIXqT5vjXCPX56wB/Ej3ViQbMSXGA8RmpEPdfdCj3Ja+3hD94nqHv5gAgtJJsAgJfYbRDzeAuY4AB/n1NFkojVx1Vwj8VHxCG9i3r7u/TPFKaZ5HxHESXjmvBZMrxgllhaXIg8jkXAgVL16t5yz0WeZACwOiEfFOwJGzgaz4fsKSmL/BC/XH6KPu5Y7DbhyW+fgwtK9ZA4J0XaPJoxWDJJRF0Ip49tDH+UDXrq7+wwMhu5bnyiFIpMt5OugjR4PRV3MNEUvD5iwHnCp+AQLyqmjBgz5wVKAViQaOqcTBV7qSv9/TxgWDKPtl1ucYfkBOk1XVcLhX4727euM2ea1DIAtCKgorfd2jUhja3OlQad0uLA57WAz+1VFlIc5g==
    username: AgCXOCuybMceQub0KYJmnEqqFVrqSPPfRs/COX1iGkTUIWr6dZ7PbI8vqgec0M5gy8HjF6MuXsVnuBIemZSVs9yTFZnAlHZplpaNdGgWOMoeYxSTMNBwKjNbQr4ZHQ+ZpqszIiugblO4RbRe3wWDLvRo/ZEUxojUU81C0/PsBbb5WhKqgI20PDnIi4o0xQ1T74w+huPAUYQkP4I14xOH092mP+FWN6xTsVTM7qBLh9SGJRMvZejsFzNWdj33P+crJxn8WWyTwC3ClCWlGRVu5vEqsAWj1hqqr2d3dCphGCaA87a3vjP7X9AEH3jCum6WY4NzTNAx8L1N7MHlpilYQMhBg84wXD3eihZ630hoyfC9UJYz4Vjk1zd2VWDpseyVYkMmDxyI4llDr2yd6428lvTBBysKhgfJi0SRIANDLuCgZt28GXlBvwP4aYipTnKl+mMew3RslFgMh81BHvY5QRguR7j111b5zM6J63Qm7SKSJe3SEnG5VTj+vmVrulXSnLu6yYJjkgIsim76laaogTDbfmIo3qwwb2/3BMlzzQzPMVxtfUbYPdpfyicH8pGIRkypjPSwrm2JHKq0R58tl35lYnRg7mgLfO/X7PxQ8Z+wnmBt/xI79SIegbxJ0obpftpoMq45DvaWwPVDcE92+51ynilv5Xzm/o9CTN5+2bBOV0KtFRlcoWpy0eRnyHI30f0xDQkjp5FiDZIJdEe3MA==
  template:
    metadata:
      name: harbor-registry-auth
      namespace: harbor
