apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-proxy-config
  labels:
    app.kubernetes.io/name: mcp-proxy
data:
  # Sample
  config.json: |
    {
      "mcpServers": {
        "context7": {
          "url": "https://mcp.context7.com/mcp"
        }
      }
    }
