---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-proxy-auth-token
  namespace: argocd
spec:
  encryptedData:
    token: AgBeUf5XaN5HUoFhGyZZsoJ3YpeBpGcZGjICdUtYy71sAKc/sLDa1bcJxusRa4f6QQJAheFOfcSoA0xeUgHgiyKgES5XbI+RORBK/mUz4ep51wex5OPxmtsdmdumVv7Pd1Ivdnaxtm9GGnU7KhF7/WIcOMbs2CSvgN85n4nM0Ga71ngKiHr10tW/6p9rDlo24c/qmljbpa/KleOv2fRt3YgLtwIwdwQoVbFmaFaQYi/c96rBA1QJ+2VFfszzd062hVwu66XYnAh294mUNZCkknjxG2OuA/2b3M7YvSAIRCa0jITjNPAZCTJcCbunC/grSnLOrblEO8KFFKmllqrtM6kacknEEysRwsgRg7bO9leI4lw4CCWkumLheqxBlZ+YBvuAhoiYEqt5rTMtZMWyWs57dGM8oFBssIbDvkqUG2PrFoEq/qsSl0JtazmQcYtZuqMocVeh658qrN7dtpwqyCiSZ9ayBoQe+s6LekwG/p+ycdXJ6xYCBuF9eDjk8bYi4f/cnsJTMaQWHx2BvoQBTgDwtlSslsbdwKJNoXG63pFplCYWWk6VZWpaM/tSvZ5q0s+i2C9NbDp6S2WBNT2z6AqmBy154H4vvWXMOvYKSyYFVc5sAc2BSIHpUuomusCj/FyDr0aUYJ6Vi4O3jh3+v+VVF0yGxxOCCQhyK8+7Y9av/+kVE1us5Z899dIPDq1SiGuezC8PNBhewfyqFR1os0HExH/I+9cC9QIDBysQ/NG5pQFHS0mELxnHE05h2SrTNcrpXfPs4Hhaxs1rDT3zSLJB
    token2: AgAlVqnAK4N2vnRq7Iq6FSP6BEezBIu0XA6C1/bKfD4ofJ3CX1BlE85PZhvew6GeOWiZniGeASC+0yKi++bCIuvSAirdqGREk6YnQGhuWDD5V/gs+csXiMg8xmTi8Vk+lVcWXxMJkBgjVc5FX4jOzeEeWDpnV2/+B6W+xbcDMumTTtcNFyIRISgbpao7sdRz/ngDBgA7p9bpmUsAfs5PeVnl0dTbeqmwTq2cAbZBX/H26kpQEwllIfkk9PhmbPBKRvOecDJCsx2YF3A28D8WmDrVa56DbAtSZcKsAdIsw/+sqUZkYAVf0E3FjIrfXupYLWDlk0DjIOGdIsAZyaqhFj5z5FnuZaZ+aMPXdCB7NRgAD8FitWmbEf395vTyEunf2jKXnxm0xAwvr8fbvzNkJJs7kq/GKLDcnXbb2fTHlakGgkXKNp55O35Sht3T/sXl29W5KXMqcOwlkW8WUhGLhBDV/DpGLX2H9BxTdL8tSoDfwRCMecLlnhZ9gKeGxVvdjr2S+ZmQWNksVBVCw1neteX3s0JFz7VUMWmt8u+s9o/4xPof/m79Dhs6Ub9DID4LaGx6dtzFjZa2vvrSxz1tm7eebSqBOpNHMuHs7hkttI/Gekxg2IMttW9enKJDWlSScA+kd0Fty1yb5HImT8iBHWWcK7OPnFd0xpToF3Y06q7F9MrOU9GZ1+VbOWMsdBw0A0CsbcZLnrg/zxDjsjfnzX57T1iXYWtqouSCku58AmhDiz2x/R6d6dj+4qOP0sHQgDQTionVHpwuuZxhqAoXr2rt
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp-proxy
      name: mcp-proxy-auth-token
      namespace: argocd
    type: Opaque
