---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-proxy-auth-token
  namespace: mcp-proxy
spec:
  encryptedData:
    token: AgBz2COYiIUcM7VpfWhCjkjKVtdXI0mF9FmEQl8PXZcqnaEV/sXnvy5NXk5WahygtQl14XKJrRo9gpubyF3jrzSE2hDZwnOVGLCd+MMqv8wU1DMEigFz58esK+zfjiTZLQFuXcnc4XL4+pxS2+qAEZYEa1GgBEeTRAaAlsWnlX/fiu33uoNInkgFSHUhHHOpltY9YMIch4OK23hsYNOlrHBJ4l1ESfXl9cPN19C4v4lvxY2Kqf2i+IGuqpuNrajkSqGXJHYF3/KkuOEkS9CKVoJ6wTHI4grcVfNSToObeJI1qp/6q+J8NFwPcibmuL4JqsajcisTL/TA5mAibB2crT6A6TF3CBQ5GQgUb5PfUcNb2bavWn/G7vTVdfU8TsRH+8sHVekMXOAQ14R2T1v513MM9yArtkQvelBbMjV9QDtddOEtgGwG58a7WHo8aWMDFGtd8cs9dwFYb5KuClPhF5CKHTR9iIARGhFwCeqim3N6kpJoyFcpU5Z+iA+8R7mo42CoBHOdSNhFrdy3Ln5L1PYQdKu1Blz8SbuuSoilHDy4wd9qQk2tEv1C/MSxWoiYyn+j2o1eviA6lmPNpmsItXSqEiGDVXO2yq9tL+3aTdomM1078g7WqGfN1M9ahSiVZsmjEqoDmDWYIVK1g9FtHo+eziZ7DXtRt5f9mJ36czEjrOZO4QNdbfTwo5X/BVapoFQ8acJMUoKHrgatSzCdbj825fRWNlCFvMHGRY2K8F7NWgluSkfomwueue5fLslB6ka0VGWbAsLB4+kTFkAOX4f8
    token2: AgBtKlV73d2lJnV2j6FO+KlPZYz4ZO0NpeGIQdtDiz1uXaOog6fAYxOw0hDYB+peutAQs7KIhakz8AjvB1Pw84JlOwKXsF2/BUxgcLlpFEyhbzkOQsrG2CdYPxYDfQ5U3F/zYpuwtGF351/sKOnlKED3zxYf//F14JaN+UrQ1cOfSrHwLl0RPk5jFMg4urq3vuKB9OKZomcw8tB92o09vhRCLaXFrvSJVewOwK60vXWLFi9UlhKB+DJWZJiPkwm0+vSupKlEFNjBsdADkvWx8U0sQEHcC1aZ0Y2u3aHkQQ+OM9rlAQVabBt0JY7YcppiQODH2tPHyVgkzh9eycKWr/ZduR6OIYQZrdEjSumvLYcKmpxos6gppEesm4TgwTEAjpU8F51v5A3gOQzPCOPDzih//qdNPJZRz2FXK21dqEH+KkFffeBf/NUyjp6POGfpbSCmNEvbmdPJ6Ek/sWfgAwMsgxQMMPEy9W3WHVi7ARO/VZO1B6uAM0hHr+M8uxwjSBnZ3NgEzRXgyphyltoyqnJromg1dnA9VMkqTRwWQTghOZNpVNNIw/TUVZPQqnnbSX8hMMUftKj+w60xaKYvco+XG+e4r7inBVE9cluTV2bFQ3Fju4p6X+b7uIkw6S28yCQCU9Va7zn6oZ4L6d0OOv7SlJ+h/hYM72UKgID3JYEg6KfoBWianhqcf6C0u9AjnqJ5bZd/TDlzY5X+xJkmcKDsVCEG/E/nmcIJ8narzXo8w6zq4gQ0Xe//Kjeiy4udXo/svLx+QMKYLfkbE6XLc30x
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mcp-proxy
      name: mcp-proxy-auth-token
      namespace: mcp-proxy
    type: Opaque
