apiVersion: v1
kind: ConfigMap
metadata:
  name: mcpu-config
  labels:
    app.kubernetes.io/name: mcp-proxy
data:
  config.json: |
    {
      "deepwiki": {
        "type": "http",
        "url": "https://mcp.deepwiki.com/mcp"
      },
      "searxng": {
        "type": "http",
        "url": "http://searxng-mcp.mcp-proxy.svc.cluster.local:3000/mcp"
      },
      "firecrawl": {
        "type": "http",
        "url": "http://firecrawl-mcp.firecrawl.svc.cluster.local:8080/v2/mcp"
      }
    }
