---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: openwebui-postgres
  namespace: openwebui
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/part-of: application
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie

  primaryUpdateStrategy: unsupervised

  postgresql:
    extensions:
      - name: pgvector
        image:
          # renovate: suite=trixie-pgdg depName=postgresql-18-pgvector
          reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie

  bootstrap:
    initdb:
      database: openwebui
      owner: openwebui
      secret:
        name: openwebui-postgres-auth
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;

  storage:
    size: 5Gi
    storageClass: longhorn

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
