apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - dawarich-app-service.yaml
  - dawarich-ingress.yaml
  - dawarich-app-pod.yaml
  - dawarich-db-data-persistentvolumeclaim.yaml
  - dawarich-db-deployment.yaml
  - dawarich-public-persistentvolumeclaim.yaml
  - dawarich-redis-data-persistentvolumeclaim.yaml
  - dawarich-redis-deployment.yaml
  - dawarich-shared-persistentvolumeclaim.yaml
  - dawarich-sidekiq-pod.yaml
  - dawarich-storage-persistentvolumeclaim.yaml
  - dawarich-watched-persistentvolumeclaim.yaml
